from gym.envs.registration import register

register(id="Merging-v0", entry_point="driving_envs.envs:MergingEnv")
register(id="Merging-v2", entry_point="driving_envs.envs:MergingEnv2")
register(id="Merging-v3", entry_point="driving_envs.envs:MergingEnv3")
register(id="Merging-v4", entry_point="driving_envs.envs:MergingEnv4")
register(id="Merging-v5", entry_point="driving_envs.envs:MergingEnv5")
register(id="Merging-v6", entry_point="driving_envs.envs:MergingEnv6")
register(id="Merging-v7", entry_point="driving_envs.envs:MergingEnv7")
register(id="Merging-v8", entry_point="driving_envs.envs:MergingEnv8")
register(id="Merging-v9", entry_point="driving_envs.envs:MergingEnv9")
register(id="Merging-v10", entry_point="driving_envs.envs:MergingEnv10")
register(id="Merging-v11", entry_point="driving_envs.envs:MergingEnv11")
register(id="Merging-v12", entry_point="driving_envs.envs:MergingEnv12")
register(id="Merging-v13", entry_point="driving_envs.envs:MergingEnv13")
register(id="Merging-v14", entry_point="driving_envs.envs:MergingEnv14")
register(id="Navigation-v0", entry_point="driving_envs.envs:NavigationEnv")
register(id="Navigation-v2", entry_point="driving_envs.envs:NavigationEnv2")
register(id="Navigation-v3", entry_point="driving_envs.envs:NavigationEnv3")
register(id="Navigation-v31", entry_point="driving_envs.envs:NavigationEnv31")
register(id="Navigation-v4", entry_point="driving_envs.envs:NavigationEnv4")
register(id="Navigation-v41", entry_point="driving_envs.envs:NavigationEnv41")
register(id="ObstacleAvoidance-v0", entry_point="driving_envs.envs:ObstacleAvoidanceEnv")
