from gym.envs.registration import register

#register(id="Merging-v0", entry_point="driving_envs.envs:MergingEnv")
#register(id="Merging-v2", entry_point="driving_envs.envs:MergingEnv2")
#register(id="Merging-v3", entry_point="driving_envs.envs:MergingEnv3")
#register(id="Merging-v4", entry_point="driving_envs.envs:MergingEnv4")
#register(id="Merging-v5", entry_point="driving_envs.envs:MergingEnv5")
#register(id="Merging-v6", entry_point="driving_envs.envs:MergingEnv6")
#register(id="Merging-v7", entry_point="driving_envs.envs:MergingEnv7")
#register(id="Merging-v8", entry_point="driving_envs.envs:MergingEnv8")
#register(id="Merging-v9", entry_point="driving_envs.envs:MergingEnv9")
#register(id="Merging-v10", entry_point="driving_envs.envs:MergingEnv10")
#register(id="Merging-v11", entry_point="driving_envs.envs:MergingEnv11")
#
#register(id="Obstacle-v0", entry_point="driving_envs.envs:ObstacleAvoidanceEnv")
#register(id="Obstacle-v2", entry_point="driving_envs.envs:ObstacleAvoidanceEnv2")
#register(id="Obstacle-v3", entry_point="driving_envs.envs:ObstacleAvoidanceEnv3")
#register(id="Obstacle-v4", entry_point="driving_envs.envs:ObstacleAvoidanceEnv4")
#register(id="Obstacle-v5", entry_point="driving_envs.envs:ObstacleAvoidanceEnv5")
#register(id="Obstacle-v6", entry_point="driving_envs.envs:ObstacleAvoidanceEnv6")
#register(id="Obstacle-v7", entry_point="driving_envs.envs:ObstacleAvoidanceEnv7")
#register(id="Obstacle-v8", entry_point="driving_envs.envs:ObstacleAvoidanceEnv8")
#register(id="Obstacle-v9", entry_point="driving_envs.envs:ObstacleAvoidanceEnv9")

register(id="Continuous-v0", entry_point="driving_envs.envs:GridworldContinuousEnv")
register(id="ContinuousMultiObjLL-v0", entry_point="driving_envs.envs:GridworldContinuousMultiObjLLEnv")
register(id="ContinuousMultiObjRR-v0", entry_point="driving_envs.envs:GridworldContinuousMultiObjRREnv")
register(id="ContinuousMultiObjLR-v0", entry_point="driving_envs.envs:GridworldContinuousMultiObjLREnv")
register(id="ContinuousMultiObjRL-v0", entry_point="driving_envs.envs:GridworldContinuousMultiObjRLEnv")
register(id="ContinuousNoneLL-v0", entry_point="driving_envs.envs:GridworldContinuousNoneLLEnv")
register(id="ContinuousNoneRR-v0", entry_point="driving_envs.envs:GridworldContinuousNoneRREnv")
register(id="ContinuousNoneLR-v0", entry_point="driving_envs.envs:GridworldContinuousNoneLREnv")
register(id="ContinuousNoneRL-v0", entry_point="driving_envs.envs:GridworldContinuousNoneRLEnv")
